//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DormApp.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public int id_account { get; set; }
        public int id_person { get; set; }
        public decimal sum { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
