//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DormApp.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agreement
    {
        public int id_agreement { get; set; }
        public int person_id { get; set; }
        public int dorm_id { get; set; }
        public int floor_number { get; set; }
        public int room_number { get; set; }
        public int room_id { get; set; }
        public System.DateTime date_open { get; set; }
        public System.DateTime date_end { get; set; }
        public bool is_active { get; set; }
    
        public virtual DormType DormType { get; set; }
        public virtual Person Person { get; set; }
        public virtual RoomType RoomType { get; set; }
    }
}
