//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DormApp.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        public long id { get; set; }
        public string admin_name { get; set; }
        public int dorm_id { get; set; }
        public string description { get; set; }
        public Nullable<bool> debitAccountFlag { get; set; }
        public Nullable<bool> insertFlag { get; set; }
        public Nullable<bool> changeRoomFlag { get; set; }
        public Nullable<bool> moveOutFlag { get; set; }
        public Nullable<bool> addPriceFlag { get; set; }
        public Nullable<bool> addPaymentFlag { get; set; }
    
        public virtual DormType DormType { get; set; }
    }
}
