//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DormApp.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mail
    {
        public long id { get; set; }
        public string email { get; set; }
        public int person_id { get; set; }
        public string password { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
